export interface PartnerAddressModel{
    partnerId:number;
    addressId:number;
    addressName:string;
    firstName:string;
    secondName:string;
    address1:string;
    address2:string;
    zipCode:string;
    town:string;
    state:string;
    countryId:string;
    telefone:string;
    mail:string;
    salesmanId:number;
    isCommercialAddress:boolean;
    isDeliveryAddress:boolean;
    isInvoicingAddress:boolean;
}
